Improved: Set timezone from luxon settings instead of moment(#2dewerv)
hotwax/picking pull request #60
Opened 2022-07-06 07:52 UTC by shashwatbangar

### Related Issues

Closes #
https://github.com/hotwax/picking/commit/c6aaf633bedbb408c20d326e1358c842aa0a5339

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

2022-07-08 12:19 UTC, disha1202 requested changes

2022-07-08 12:19 UTC, disha1202 commented on package.json
> +    "vue-loader-v16": "^16.0.0-beta.5.4"
Revert unwanted changes.

2022-07-08 12:19 UTC, disha1202 commented on src/main.ts
>      // TODO Use Loxon instead
We can remove this TODO now.

2022-07-08 12:24 UTC, shashwatbangar commented on src/main.ts
>      // TODO Use Loxon instead
Sure. Fixed it.

2022-07-08 12:26 UTC, shashwatbangar commented on package.json
> +    "vue-loader-v16": "^16.0.0-beta.5.4"
Done.

2023-02-02 13:08 UTC, k2maan commented
Closing as already implemented.

2023-02-02 13:08 UTC, closed without merging