Upgraded to ionic 6.2.9 (#2w9wz26)
hotwax/picking pull request #95
Opened 2023-01-09 11:34 UTC by k2maan

### Related Issues

Closes #85 

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

2023-01-09 12:18 UTC, disha1202 approved these changes

2023-01-10 10:24 UTC, adityasharma7 requested changes

2023-01-10 10:24 UTC, adityasharma7 commented on .eslintrc.js
>      'no-console': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
```suggestion
    'no-console': 'off',
```

2023-01-10 10:32 UTC, adityasharma7 approved these changes

2023-01-10 10:32 UTC, merged